name: Deploy Master

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Print GitHub Context # Debug step
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.0
      - run: npm install -g yarn
      - run: yarn
      - run: yarn build
      - run: yarn upload:algolia
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
