name: Check PR

on: pull_request

jobs:
  test:
    name: All tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Print GitHub Context # Debug step
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.0
      - run: npm install -g yarn
      - run: yarn
      - run: yarn lint
      - run: yarn test
        env:
          CI: true
